global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'my-app'
    static_configs:
      - targets: ['localhost:8081']  # Change this to the port where metrics are exposed

